task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 393

train_dataset:
    data_root: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_393/annots.npy'
    split: 'train'

test_dataset:
    data_root: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_393/annots.npy'
    split: 'test'

# data options
num_train_frame: 300
training_view: [0]
