task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_377.yaml'

human: 313

train_dataset:
    data_root: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_377/annots.npy'
    split: 'train'

test_dataset:
    data_root: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_377'
    human: 'CoreView_377'
    ann_file: '/cluster/scratch/tguillou/nb_data/zju_mocap/CoreView_377/annots.npy'
    split: 'test'

# data options
training_view: [0]
